export const FETCH_EVENTS = {
  START: 'FETCH_EVENTS',
  SUCCESS: 'FETCH_EVENTS_SUCCESS',
  ERROR: 'FETCH_EVENTS_ERROR',
};

export const SELECT_EVENTS = 'SELECT_EVENTS';
export const SHOW_EVENTS_PANEL = 'SHOW_EVENTS_PANEL';
export const HIDE_EVENTS_PANEL = 'HIDE_EVENTS_PANEL';
